### PR TITLE
Get company profile

### PR DESCRIPTION
**Pull request by RafailFerre**
Created companyGet.spec, companyHelper, add userId in constants, userHelper for alternative getting userId

### CODE REVIEW

**Comment by dumpdusty** [comment]
conflicts has to be resolved

**Comment by RafailFerre** [comment]
Updated companyGet.spec.js
Created new constatnts: companyId
Updated companyHelper

**Review by dumpdusty — DISMISSED** [review]
LGTM!

**Review by dashakhan — APPROVED** [review]

**Review by dumpdusty — APPROVED** [review]
all good so far!

**Pull request merged**
