### PR TITLE
This PR adds README.md file 

### PR DESCRIPTION
**Pull request by dumpdusty**
Readme file will add full explanation of the project with all necessary details.

### CODE REVIEW

**Review by ZdanovichOleg — DISMISSED** [review]

**Comment by RafailFerre** [comment]
> Readme file will add full explanation of the project with all necessary details.

Found a little mistake: 
> [ClientBase CRM version **5**](https://clientbase.pasv.us/v6) 
for version 5 or 6 correct?

**Comment by dumpdusty** [comment]
> > Readme file will add full explanation of the project with all necessary details.
> 
> Found a little mistake:
> 
> > [ClientBase CRM version **5**](https://clientbase.pasv.us/v6)
> > for version 5 or 6 correct?

6 for sure, tnx for mentioning, typo fixed

**Review by RafailFerre — APPROVED** [review]
looks good

**Review by dashakhan — APPROVED** [review]
Looks good 👍

**Review by ZdanovichOleg — APPROVED** [review]

**Pull request merged**
